
trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps: 
- script: npm install
  displayName: Downloaddependices 
- task: Docker@2
  inputs:
    containerRegistry: 'docker_registry'
    repository: '000100000/cartnew'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'