trigger:
- main 

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: ci
  jobs:
  - job: trigger
    steps:
    - script: |
        npm install
        ls -lrt
    - task: Docker@2
      inputs:
      containerRegistry: 'docker_registry'
       repository: '000100000/cartnew'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'