trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CIthinks
  jobs:
  - job: CIWork
    steps:
    - script: | 
        npm install
      displayName: Download dependinces

- stage: buildpush
  jobs:
  - job: TestWork
    steps:
    - script: |
       docker login -u 000100000 -p Orange@012
       docker tag 000100000/cartnew 000100000/cartnew:latest
       docker push 000100000/cartnew:latest

   


    






