trigger:
- main 

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: ci
  jobs:
  - job: trigger
    steps:
    - script: echo super1
- stage: secondscript
  jobs:
  - job: secondjob
    steps:
    - script: echo super2
  displayName: ryder 




   

    






