trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: npm install
    displayName: Download dependinces
  
  - script: docker build -t 000100000/cartnew .
    displayName: building docker image
       
 - task: Docker@2
   inputs:
    containerRegistry: 'docker_registry'
    repository: '000100000/cartnew'
    command: Push'
    






