trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: npm install
    displayName: Download dependinces
  
  - script: docker build -t 000100000/cartnew .
    displayName: building docker 
    
  - script: |
      sh docker login -u  000100000/cartnew -p Orange@012


    






