trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: npm install
    displayName: Download dependinces
  
  - script: docker build -t cart .
    displayName: building docker image
    






