trigger:
- main 

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  jobs:
  - job: CI
    steps:
    - script: env
      displayName: env
    - script: npm install
      displayName: Downlaod NodeJS Dependencies
    - script: docker build -t 000100000/cartnew .
      displayName: Docker Build

- stage: DockerUpload
  condition: succeeded('CI')
  jobs:
  - job: DockerUpload
    steps:
    - task:
      inputs:
       containerRegistry: 'docker_registry'
       repository: '000100000/cartnew'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'
       tags: 'latest':latest







