trigger:
- main 

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: ci
  jobs:
  - job: trigger
    steps:
    - script: |
        npm install
        ls -lrt
        docker build -t 000100000/cartnew .
        docker images

- stage: secondscript
  condition: succeeded()
  jobs:
  - job: secondjob
    steps:
    - script: |
       docker login -u 000100000 -p Orange@012
       docker tag 000100000/cartnew 000100000/cartnew:latest
       docker push 000100000/cartnew:latest
  displayName: ryder 




   

    






