trigger:
- main 

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: ci
  jobs:
  - job: cijob
    steps:
    - script:
        npm install
 - stage: second
   jobs:
   - job: secondjob
   steps:
   - script: echo supeer



   

    






