trigger:
- main



pool: 
    vmImage: 'ubuntu-latest'

variables:
  COMPONENT: cart

resources:
  repositories:
    - repository: templates
      type: github
      name: anadu/roboshop-azure-devops-templates
      endpoint: anadu

stages:
- template: nodejs.yml@templates
- task: Docker@2
  inputs:
    containerRegistry: 'docker registry'
    repository: 'cart'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

