trigger:
- main

pool: D65

variables:
  COMPONENT: cart


resources:
  repositories:
    - repository: templates
      type: github
      name: raghudevopsb65/roboshop-azure-devops-templates

stages:
- template: nodejs.yml

