trigger:
- main

pool: 
    vmImage: 'ubuntu-latest'

variables:
  COMPONENT: cart

resources:
  repositories:
    - repository: templates
      type: github
      name: anadu/roboshop-azure-devops-templates
      endpoint: anadu

'

